/* GlideTalks Article Data */

const ARTICLES = [
  {
    slug: "mid-server-the-engine-behind-discovery-orchestration-and-integrations",
    title: "MID Server: The Engine Behind Discovery, Orchestration, and Integrations",
    excerpt: "\nEvery ServiceNow architect eventually learns this truth: your instance is only as good as your MID Servers. The MID servers are the invisible workhorses that connect your...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Nov 2025",
    readTime: "6 min read",
    tags: ["ServiceNow", "ServiceMapping", "Discovery", "ITOM", "Cloud"],
    featured: true
  },
  {
    slug: "the-05-pillars-of-servicenow-ai-control-tower",
    title: "The 5 Pillars of ServiceNow AI Control Tower",
    excerpt: "\n\n\n\n\nIn the first part of this series on ServiceNow AI control tower, we talked about why enterprises need AI Control Tower and the chaos it solves and the confidence it...",
    category: "ai",
    categoryLabel: "AI",
    categoryIcon: "&#129302;",
    date: "Nov 2025",
    readTime: "3 min read",
    tags: ["ServiceNow", "AI", "Control", "Tower", "Pillar", "Ecosystem"],
    featured: false
  },
  {
    slug: "cloning-breaks-your-service-graph-connectors",
    title: "When Cloning Breaks Your Service Graph Connectors: Lessons from AWS & Azure Integrations in ServiceNow",
    excerpt: "\nIf you have ever worked with Service Graph Connectors in ServiceNow especially the ones for AWS or Azure you probably know how powerful they are. They make the CMDB smarter by...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Oct 2025",
    readTime: "3 min read",
    tags: ["ServiceNow", "ITOM", "Cloud", "ServiceGraph", "Connectors", "Cloning"],
    featured: false
  },
  {
    slug: "introduction-to-servicenow-ai-control-tower",
    title: "Introduction to ServiceNow AI Control Tower",
    excerpt: "\nLet’s be honest, AI is everywhere right now. From the chatbots answering our customers to the models predicting what we’ll buy next week, every organization is racing to infuse...",
    category: "ai",
    categoryLabel: "AI",
    categoryIcon: "&#129302;",
    date: "Oct 2025",
    readTime: "3 min read",
    tags: ["ServiceNow", "AI"],
    featured: false
  },
  {
    slug: "securing-mid-servers-in-fedramp-servicenow-with-mtls",
    title: "Securing MID Servers in FedRAMP ServiceNow with mTLS",
    excerpt: "\nIn a FedRAMP compliant ServiceNow environment, storing usernames and passwords for MID Servers is not allowed even if encrypted. To meet these strict security requirements, the...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Aug 2025",
    readTime: "4 min read",
    tags: [],
    featured: false
  },
  {
    slug: "from-blueprints-to-build-designing-servicenow-instances-data-flows-and-integrations",
    title: "From Blueprints to Build: Designing ServiceNow Instances, Data Flows, and Integrations",
    excerpt: "\nIn the first article of this series, we talked about why architecture matters and how it sets the stage for everything you will do on the ServiceNow Platform. Now let us shift...",
    category: "platform",
    categoryLabel: "Platform",
    categoryIcon: "&#128274;",
    date: "Aug 2025",
    readTime: "4 min read",
    tags: ["ServiceNow", "AssetManagement", "Strategy", "Platform", "Architecture"],
    featured: false
  },
  {
    slug: "managing-and-expanding-your-servicenow-architecture",
    title: "Managing and Expanding Your ServiceNow Architecture",
    excerpt: "\nIn the first two articles of this series, we explored why planning architecture matters and how to design your instances, data flows, and integrations. But here’s the truth:...",
    category: "ea",
    categoryLabel: "EA",
    categoryIcon: "&#127959;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: [],
    featured: false
  },
  {
    slug: "the-hidden-foundation-of-servicenow-success-planning-your-architecture",
    title: "The Hidden Foundation of ServiceNow Success: Planning Your Architecture",
    excerpt: "\nMost organizations that adopt ServiceNow do so with excitement. Dashboards, automation, AI-powered workflows and the promise feels limitless. But here\'s the catch: without the...",
    category: "ea",
    categoryLabel: "EA",
    categoryIcon: "&#127959;",
    date: "Aug 2025",
    readTime: "4 min read",
    tags: [],
    featured: false
  },
  {
    slug: "the-denyall-mindset-implementing-servicenow-itom-solutions-in-government-and-defense-envionments",
    title: "The DenyAll Mindset: Implementing ServiceNow ITOM Solutions in Government and Defense Environments",
    excerpt: "\nWhen deploying ServiceNow ITOM solutions in highly secure environments, technology alone isn’t enough. It\'s how you secure the interactions between systems that truly defines...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: [],
    featured: false
  },
  {
    slug: "troubleshooting-service-mapping-in-deny-all-permit-by-exception-environments",
    title: "Troubleshooting Service Mapping in Deny-All, Permit-by-Exception Environments",
    excerpt: "\nIn complex enterprise environments, building accurate service maps often comes with unique challenges. This is especially true when working in deny-all, permit-by-exception...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: ["ServiceNow", "ServiceMapping", "Discovery", "ITOM", "Cloud"],
    featured: false
  },
  {
    slug: "it4it-version-3-0-a-new-era-for-managing-it-part-1",
    title: "IT4IT Version 3.0: A New Era for Managing IT (Part 1)",
    excerpt: "\nThe release of IT4IT Version 3.0 is more than just an update. It is a turning point in how organizations think about managing IT in today’s digital-first world.We are moving...",
    category: "it4it",
    categoryLabel: "IT4IT",
    categoryIcon: "&#128218;",
    date: "Aug 2025",
    readTime: "4 min read",
    tags: [],
    featured: false
  },
  {
    slug: "it4it-version-3-0-a-new-era-for-managing-it-part-2",
    title: "IT4IT Version 3.0: A New Era for Managing IT (Part 2)",
    excerpt: "\n\n to the Functional Components\n\n\n\nIn IT4IT Version 2.1, the framework was organized around four value streams:\n\n\n\n\nStrategy to Portfolio\n\n\n\nRequirement to...",
    category: "it4it",
    categoryLabel: "IT4IT",
    categoryIcon: "&#128218;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: [],
    featured: false
  },
  {
    slug: "demystifying-cmdb-lifecycle-stage-and-status-in-servicenow",
    title: "Demystifying CMDB Lifecycle Stage and Status in ServiceNow",
    excerpt: "\nFeeling lost with ServiceNow Lifecycle Stages? You are not alone. Many people find the terminology a bit overwhelming at first. The good news is that these stages are not as...",
    category: "csdm",
    categoryLabel: "CSDM",
    categoryIcon: "&#9729;&#65039;",
    date: "Aug 2025",
    readTime: "4 min read",
    tags: ["ServiceNow", "CMDB", "LifecycleStage", "AssetManagement", "ITSM", "CSDM"],
    featured: false
  },
  {
    slug: "what-does-it4it-mean",
    title: "What Does “IT4IT” Mean?",
    excerpt: "\nAt first, the name IT4IT might make you pause. It almost feels like a tongue twister - “IT for IT.” And that’s actually the point. But there is more to it than just a clever...",
    category: "it4it",
    categoryLabel: "IT4IT",
    categoryIcon: "&#128218;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: ["CSDM", "IT4IT"],
    featured: false
  },
  {
    slug: "when-trust-goes-both-ways-tls-vs-mtls-explained-simply",
    title: "When Trust Goes Both Ways: TLS vs mTLS Explained Simply",
    excerpt: "\nIn today’s digital world, trust is everything. Whether you are logging into your bank, shopping online, or connecting systems inside a company, you want two things:\n\n\n\n\nTo...",
    category: "itom",
    categoryLabel: "ITOM",
    categoryIcon: "&#9881;",
    date: "Aug 2025",
    readTime: "3 min read",
    tags: ["ServiceNow", "ServiceMapping", "Discovery", "ITOM", "Cloud"],
    featured: false
  }
];
